project:
  type: website
  output-dir: docs

website:
  title: "Youngjun Kim"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - posts.qmd
      - icon: github
        href: https://github.com/yjkim93
      - icon: linkedin
        href: https://www.linkedin.com/in/yjkimmuno/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



