{
  "hash": "e6f93f9c21a4948b9806d580c7719b4e",
  "result": {
    "markdown": "---\ntitle: \"Spatial Transcriptomics Data Analysis Tutorial 02: Quality Control\"\ndescription: \"This tutorial covers the preparation steps for spatial transcriptomics data analysis using Bioconductor.\"\nauthor:\n  - name: Youngjun Kim\n    url: https://yjkim93.github.io\n    orcid: 0000-0003-3346-9457\ndate: 12-21-2025\ncategories: [spatial-transcriptomics, bioconductor, R]\ncitation:\n  url: https://yjkim93.github.io/posts/2025-12-21-spatial-transcriptomics-02-qc/\ndraft: false\nexecute:\n  warning: false\neditor: source\n---\n\n\n# 2. Quality Control (QC)\n\n## Load packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(SpatialExperiment)\nlibrary(SpotSweeper)\nlibrary(scuttle)\nlibrary(scater)\nlibrary(ggside)\nlibrary(ggplot2)\nlibrary(escheR)\nlibrary(HDF5Array)\nlibrary(ggspavis)\nlibrary(patchwork)\n```\n:::\n\n\n## Load Data\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvisium_data_path <- file.path(data_path, \"raw_colon_cancer\")\nhdf_data_path <- file.path(data_path, \"hdf5_colon_cancer\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nspe <- loadHDF5SummarizedExperiment(\n  dir = hdf_data_path,\n  prefix = \"01_subsetted_\"\n)\n```\n:::\n\n\n## Calculate QC metrics\n\nFirst, we calculate the QC metrics for each spot using `scuttle::addPerCellQCMetrics()`. On top of the basic QC metrics (library size, number of detected genes), we will also compute the mitochondrial proportion using `subsets` argument. Mitochondrial genes are typically prefixed with \"MT-\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# grep returns the index number that matches the regex\n# grepl returns a logical vector where TRUE indicates a match.\nis.mito <- rownames(spe)[grepl(\"^MT-\", rownames(spe))]\nprint(c(\"Column names before adding QC metrics:\", colnames(colData(spe))))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"Column names before adding QC metrics:\"\n[2] \"barcode\"                               \n[3] \"in_tissue\"                             \n[4] \"array_row\"                             \n[5] \"array_col\"                             \n[6] \"bin_size\"                              \n[7] \"sample_id\"                             \n```\n:::\n\n```{.r .cell-code}\nspe <- addPerCellQCMetrics(spe, subsets = list(Mito = is.mito))\nprint(c(\"Column names after adding QC metrics:\", colnames(colData(spe))))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"Column names after adding QC metrics:\"\n [2] \"barcode\"                              \n [3] \"in_tissue\"                            \n [4] \"array_row\"                            \n [5] \"array_col\"                            \n [6] \"bin_size\"                             \n [7] \"sample_id\"                            \n [8] \"sum\"                                  \n [9] \"detected\"                             \n[10] \"subsets_Mito_sum\"                     \n[11] \"subsets_Mito_detected\"                \n[12] \"subsets_Mito_percent\"                 \n[13] \"total\"                                \n```\n:::\n:::\n\n\nWe can see that six new columns have been added. - `sum`: Total UMI counts (library size) for each spot - `detected`: Number of detected genes for each spot - `subsets_Mito_sum`: Total UMI counts from mitochondrial genes for each spot - `subsets_Mito_detected`: Number of detected mitochondrial genes for each spot - `subsets_Mito_percent`: Percentage of mitochondrial gene expression for each spot - `total`: Total UMI counts from all genes for each spot (same as `sum`)\n\n## Outlier detection\n\n### Global outlier detection using fixed thresholds\n\nOne way to detect low-quality spots is to use fixed thresholds for QC metrics. We can set the thresholds based on the global distrubution of the QC metrics across all spots.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot library size vs. detected genes\np1 <- ggcells(spe, aes(x = detected, y = sum)) +\n  geom_point() +\n  geom_density_2d() +\n  scale_x_log10() +\n  scale_y_log10() +\n  geom_xsidehistogram() +\n  geom_ysidehistogram() +\n  labs(y = \"Number of UMIs\", x = \"Number of detected genes\") +\n  ggtitle(\"Library size vs. detected\")\n\n# Plot mito proportion vs. detected genes\np2 <- ggcells(spe, aes(x = detected, y = subsets_Mito_percent)) +\n  geom_point() +\n  geom_density_2d() +\n  scale_x_log10() +\n  geom_xsidehistogram() +\n  geom_ysidehistogram() +\n  labs(y = \"% mitochondrial reads\", x = \"Number of detected genes\") +\n  ggtitle(\"Mito proportion vs. genes detected\")\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/plot-qc-metrics-1.png){width=672}\n:::\n:::\n\n\nBased on the distribution, we can set thresholds for filtering low-quality spots. Here, we will use fixed thresholds for minimum library size (120), minimum number of detected genes (100), and maximum mitochondrial proportion (35%).\n\nWe can visualize these thresholds on the plots.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlib_size_min_cutoff <- 120\ndetected_genes_min_cutoff <- 100\nmito_prop_max_cutoff <- 35\n\n# Plot library size vs. detected genes\np1 <- ggcells(spe, aes(x = detected, y = sum)) +\n  geom_point() +\n  geom_density_2d() +\n  scale_x_log10() +\n  scale_y_log10() +\n  geom_xsidehistogram() +\n  geom_ysidehistogram() +\n  geom_vline(xintercept = lib_size_min_cutoff, col = \"red\", lty = 2) +\n  geom_hline(yintercept = detected_genes_min_cutoff, col = \"red\", lty = 2) +\n  labs(y = \"Number of UMIs\", x = \"Number of detected genes\") +\n  ggtitle(\"Library size vs. detected\")\n\n# Plot mito proportion vs. detected genes\np2 <- ggcells(spe, aes(x = detected, y = subsets_Mito_percent)) +\n  geom_point() +\n  geom_density_2d() +\n  scale_x_log10() +\n  geom_xsidehistogram() +\n  geom_ysidehistogram() +\n  geom_vline(xintercept = lib_size_min_cutoff, col = \"red\", lty = 2) +\n  geom_hline(yintercept = mito_prop_max_cutoff, col = \"red\", lty = 2) +\n  labs(y = \"% mitochondrial reads\", x = \"Number of detected genes\") +\n  ggtitle(\"Mito proportion vs. genes detected\")\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/set-filter-cutoffs-1.png){width=672}\n:::\n:::\n\n\nWe apply the filter and mark spots that are considered global outliers based on the set thresholds.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspe$lib_size_global_outliers <- spe$sum < lib_size_min_cutoff\nspe$detected_global_outliers <- spe$detected < detected_genes_min_cutoff\nspe$mito_prop_global_outliers <- spe$subsets_Mito_percent > mito_prop_max_cutoff\n\nspe$global_outliers <-\n  spe$lib_size_global_outliers |\n  spe$detected_global_outliers |\n  spe$mito_prop_global_outliers\n\nqc <- grep(\"global_outliers$\", names(colData(spe)))\nsapply(colData(spe)[qc], table)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      lib_size_global_outliers detected_global_outliers\nFALSE                    13252                    13207\nTRUE                       955                     1000\n      mito_prop_global_outliers global_outliers\nFALSE                     13617           12693\nTRUE                        590            1514\n```\n:::\n:::\n\n\nOut of 14,207 spots, 1,514 (around 10%) are considered global outliers based on the fixed thresholds.\n\nWe can visualize these spots.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- plotObsQC(\n  spe,\n  plot_type = \"spot\",\n  annotate = \"lib_size_global_outliers\",\n) +\n  ggtitle(paste0(\"Library size <\", lib_size_min_cutoff))\n\np2 <- plotObsQC(\n  spe,\n  plot_type = \"spot\",\n  annotate = \"detected_global_outliers\",\n) +\n  ggtitle(paste0(\"Detected genes <\", detected_genes_min_cutoff))\n\np3 <- plotObsQC(\n  spe,\n  plot_type = \"spot\",\n  annotate = \"mito_prop_global_outliers\",\n) +\n  ggtitle(paste0(\"Mito proportion >\", mito_prop_max_cutoff, \"%\"))\n\np4 <- plotObsQC(\n  spe,\n  plot_type = \"spot\",\n  annotate = \"global_outliers\",\n) +\n  ggtitle(\"Global outliers\")\n\ngridExtra::grid.arrange(p1, p2, p3, p4, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/visualize-global-outliers-1.png){width=672}\n:::\n:::\n\n\n### Local outlier detection using SpotSweeper\n\nIn spatial transcriptomics, low-quality spots are often spatially clustered. [`SpotSweeper`](https://www.nature.com/articles/s41592-025-02713-3) leverages local neighborhoods to correct for spatial confounding to identify local outliers and regional artifacts.\n\nWe are going to use `SpotSweeper::localOutliers()` to identify local outliers for library size, number of detected genes, and mitochondrial proportion. `direction` argument specifies whether we are looking for lower or higher outliers. For library size and number of detected genes, we are interested in lower outliers, while for mitochondrial proportion, we are interested in higher outliers. The `log` argument specifies whether to log-transform the metric before calculating outliers.\n\nLocal outlier detection works as follows:\n\n1.  Identify $k$-nearest neighbors for each spot $i$ based on the spatial coordinates.\n\n2.  Calculate $Z$-score for each spot $i$ with reference to its $k$ neighbors. \n    $$\n    z_i = \\frac{0.6745 \\times (x_i - m_i)}{\\text{MAD}_i}\n    $$ \n    \n    , where $x_i$ is the QC metrics of interest, $m_i$ is the median of the QC metrics in the neighborhood, and $\\text{MAD}_i$ denotes the median absolute deviation of the metrics in the neighborhood. $0.6745$ is a constant to make the MAD comparable to standard deviation under normality assumption (mathematically, $\\text{MAD} = 0.6745 \\sigma $ for normal distribution).\n\n3.  Identify outliers based on the $Z$-scores using a threshold (default: $|z| > 3$).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspe <- localOutliers(\n  spe,\n  metric = \"sum\",\n  direction = \"lower\",\n  log = TRUE,\n)\n\nspe <- localOutliers(\n  spe,\n  metric = \"detected\",\n  direction = \"lower\",\n  log = TRUE,\n)\n\nspe <- localOutliers(\n  spe,\n  metric = \"subsets_Mito_percent\",\n  direction = \"higher\",\n  log = FALSE,\n)\n\nspe$local_outliers <-\n  as.logical(spe$sum_outliers) |\n  as.logical(spe$detected_outliers) |\n  as.logical(spe$subsets_Mito_percent_outliers)\n\nqc <- grep(\n  \"(?<!global)_outliers$\",\n  names(colData(spe)),\n  perl = TRUE\n)\nsapply(colData(spe)[, qc], table)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      sum_outliers detected_outliers subsets_Mito_percent_outliers\nFALSE        14130             14139                         14127\nTRUE            77                68                            80\n      local_outliers\nFALSE          14036\nTRUE             171\n```\n:::\n:::\n\n\nThere are 171 local outliers detected based on the three QC metrics. We can plot these outliers.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- plotQCmetrics(\n  spe,\n  metric = \"sum\",\n  outliers = \"sum_outliers\",\n  point_size = 0.4,\n  stroke = 0.75\n) +\n  ggtitle(\"Library size local outliers\")\n\np2 <- plotQCmetrics(\n  spe,\n  metric = \"detected\",\n  outliers = \"detected_outliers\",\n  point_size = 0.4,\n  stroke = 0.75\n) +\n  ggtitle(\"Detected genes local outliers\")\n\np3 <- plotQCmetrics(\n  spe,\n  metric = \"subsets_Mito_percent\",\n  outliers = \"subsets_Mito_percent_outliers\",\n  point_size = 0.4,\n  stroke = 0.75\n) +\n  ggtitle(\"Mito proportion local outliers\")\n\n\np4 <- plotObsQC(\n  spe,\n  plot_type = \"spot\",\n  annotate = \"local_outliers\",\n) +\n  ggtitle(\"local outliers\")\n\ngridExtra::grid.arrange(p1, p2, p3, p4, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/visualize-local-outliers-1.png){width=672}\n:::\n:::\n\n\nAre all local outliers also detected as global outliers?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplotObsQC(\n  spe,\n  plot_type = \"violin\",\n  x_metric = \"subsets_Mito_percent_z\",\n  annotate = \"mito_prop_global_outliers\"\n)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/compare-global-local-outliers-1.png){width=672}\n:::\n:::\n\n\nIn this plot, the y-axis shows the Z-scores calculated from SpotSweeper for mitochondrial proportion, so the spots lying above Z-score of 3 are considered local outliers. The red spots are global outliers based on the fixed threshold (35%). We can appreciate many local outliers were not detected as global outliers, indicating the advantage of using local neighborhoods to identify low-quality spots that may be missed by global thresholding.\n\n### Combine global and local outlier results\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspe$outliers <- spe$global_outliers | spe$local_outliers\nsapply(\n  colData(spe)[, c(\"global_outliers\", \"local_outliers\", \"outliers\")],\n  table\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      global_outliers local_outliers outliers\nFALSE           12693          14036    12615\nTRUE             1514            171     1592\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\np1 <- plotObsQC(\n  spe,\n  plot_type = \"spot\",\n  annotate = \"global_outliers\",\n) +\n  ggtitle(\"global outliers\")\n\np2 <- plotObsQC(\n  spe,\n  plot_type = \"spot\",\n  annotate = \"local_outliers\",\n) +\n  ggtitle(\"local outliers\")\n\np3 <- plotObsQC(\n  spe,\n  plot_type = \"spot\",\n  annotate = \"outliers\",\n) +\n  ggtitle(\"total (global + local) outliers\")\n\ngridExtra::grid.arrange(p1, p2, p3, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/visualize-combined-outliers-1.png){width=672}\n:::\n:::\n\n\n## Technical artifact detection using SpotSweeper\n\nSpatial transcriptomics data may contain regional techinal artifacts. SpotSweeper provides methods to identify two distinct types of such artifacts: dryspot artifacts and hangnail artifacts.\n\n### Dryspot artifact detection\n\nDryspot artifacts are caused by incomplete coverage of permeabilization agents, leading to regions with abnormally low RNA capture.\n\nThe authors detect dryspot artifacts by applying DBSCAN to the log-transformed library size and log-transformed number of detected genes.\n\nSince the SpotSweeper Bioconductor package currently does not implement dryspot artifact detection, we implement a custom function to detect dryspot artifacts. In the paper, the radius of the epsilon neighbor is set to 0.5, and the minimum number points to 20, so we use these parameters as default values.\n\n::: {.callout-note collapse=\"true\"}\n### Dryspot artifact detection function\n\n::: {.cell}\n\n```{.r .cell-code}\nfindDrySpotArtifacts <- function(\n  spe,\n  library_size = \"sum\",\n  num_detected_genes = \"detected\",\n  samples = \"sample_id\",\n  eps = 0.5,\n  minPts = 20,\n  name = \"dryspot_artifacts\"\n) {\n  # ===== Validity checks =====\n  ## Check if 'spe' is (or inherits from) SpatialExperiment\n  if (!inherits(spe, \"SpatialExperiment\")) {\n    stop(\n      \"Input data must be a SpatialExperiment or inherit from SpatialExperiment.\"\n    )\n  }\n\n  ## Check if library_size is in colData\n  if (!all(library_size %in% colnames(colData(spe)))) {\n    stop(\"library_size must be present in colData.\")\n  }\n\n  ## Check if num_detected_genes is in colData\n  if (!num_detected_genes %in% colnames(colData(spe))) {\n    stop(\"num_detected_genes must be present in colData.\")\n  }\n\n  ## Check if samples is in colData\n  if (!samples %in% colnames(colData(spe))) {\n    stop(\"Samples column must be present in colData.\")\n  }\n\n  ## Check if spe contains more than one sample_id\n  unique_sample_ids <- unique(colData(spe)[[samples]])\n  if (length(unique_sample_ids) > 1) {\n    stop(\n      \"The input SPE must contain only one sample. Please ensure only samples containing artifacts are passed.\"\n    )\n  }\n  # ===== Main Function =====\n  # Initialize a list to store spe for each sample\n  columnData_list <- sapply(unique_sample_ids, FUN = function(x) NULL)\n\n  for (sample in unique_sample_ids) {\n    # subset by sample\n    spe.temp <- spe[, colData(spe)[[samples]] == sample]\n\n    # Calculate log2( library size + 1 ) and log2( detected genes + 1 )\n    spe.temp$sum_log2_1p <- log2(spe.temp$sum + 1)\n    spe.temp$detected_log2_1p <- log2(spe.temp$detected + 1)\n\n    # Apply DBSCAN clustering\n    dryspot.artifacts <- dbscan::dbscan(\n      colData(spe.temp)[, c(\"sum_log2_1p\", \"detected_log2_1p\")],\n      eps = eps,\n      minPts = minPts\n    )\n    spe.temp$dryspot_artifacts <- dryspot.artifacts$cluster\n\n    # Artifact annotation based on mean library size and mean detected genes\n    # Normal cluster should have the highest mean library size and mean detected genes\n    cd <- colData(spe.temp)\n\n    means <- aggregate(\n      cd[, c(library_size, num_detected_genes)],\n      by = list(cluster = cd$dryspot_artifacts),\n      FUN = mean,\n      na.rm = TRUE\n    )\n\n    normal_cluster <- with(\n      means,\n      cluster[order(-means[[library_size]], -means[[num_detected_genes]])[1]]\n    )\n\n    spe.temp$dryspot_artifacts <- spe.temp$dryspot_artifacts != normal_cluster\n\n    # add to sample list\n    columnData_list[[sample]] <- colData(spe.temp)\n  }\n\n  # rbind the list of dataframes\n  columnData_aggregated <- do.call(rbind, columnData_list)\n\n  # replace SPE column data with aggregated data\n  colData(spe) <- columnData_aggregated\n\n  # return spe\n  return(spe)\n}\n```\n:::\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspe <- findDrySpotArtifacts(\n  spe,\n  library_size = \"sum\",\n  num_detected_genes = \"detected\",\n  eps = 0.5,\n  minPts = 20,\n)\ntable(spe$dryspot_artifacts)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFALSE  TRUE \n14205     2 \n```\n:::\n:::\n\n\nThere are only two spots marked as dryspot artifacts. We can visualize them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplotQCmetrics(\n  spe,\n  metric = \"sum\",\n  outliers = \"dryspot_artifacts\",\n  point_size = 1.1\n) +\n  ggtitle(\"Library Size\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/dryspot-artifact-visualization-1.png){width=672}\n:::\n:::\n\n\nApparently, there are no obvious dryspot artifacts in this dataset.\n\n### Hangnail artifact detection\n\nHangnail artifacts are caused by tissue damage during tissue dissection. They are often visually apparent in histological images, but do not show substantial differences in the library size, number of genes detected, or mitochondrial proportion.\n\nHowever, the authors claim that hangnails display visibly lower variance in mitochondrial ratio across spots than in non-artifact domains.\n\nThe hangnail artifact detection algorithm works as follows: \n\n1. Calculate the local variance of the mitochondiral ratio for each spot at multiple orders of neighborhood. (Five orders by default) \n2. Each order of neighborhood is defined as concentric squares (for Visium HD) around each spot. For example, order 1 includes the immediate neighboring spots, order 2 includes the next layer of neighboring spots, and so on. Therefore, for $i$-th order, neighborhoods are composed of $(2i + 1)^2 - 1 = 4i(i+1)$ spots. \n3. The multiscale local variance matrix is subjected to PCA \n4. $K$-means clustering ($K=2$) is performed on the first two PCs to distinguish hangnail artifacts from normal regions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# find artifacts using SpotSweeper\nspe <- findArtifacts(\n  spe,\n  mito_percent = \"subsets_Mito_percent\",\n  mito_sum = \"subsets_Mito_sum\",\n  n_order = 5,\n  shape = \"square\"\n)\n\ntable(spe$artifact)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nFALSE  TRUE \n 7111  7096 \n```\n:::\n:::\n\n\nAlmost half of the spots are marked as hangnail artifacts. We can visualize them.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot the spatial distribution of the detected artifacts.\nplotQCmetrics(\n  spe,\n  metric = \"subsets_Mito_percent\", # You can choose any relevant metric to display\n  outliers = \"artifact\",\n  point_size = 1.1\n) +\n  ggtitle(\"Detected Spatial Artifacts\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/hangnail-artifact-visualization-1.png){width=672}\n:::\n:::\n\n\nAgain, many spots are marked as hangnail artifacts. \n\nTo assess the validity of the detected hangnail artifacts, we can visualize the distribution of mitochondrial proportion local variance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot the spatial distribution of the detected artifacts.\np1 <- plotQCmetrics(\n  spe,\n  metric = \"k8\",\n  outliers = NULL,\n  point_size = 1.1\n) +\n  ggtitle(\"Order 1\")\n\np2 <- plotQCmetrics(\n  spe,\n  metric = \"k24\",\n  outliers = NULL,\n  point_size = 1.1\n) +\n  ggtitle(\"Order 2\")\n\np3 <- plotQCmetrics(\n  spe,\n  metric = \"k48\",\n  outliers = NULL,\n  point_size = 1.1\n) +\n  ggtitle(\"Order 3\")\n\np4 <- plotQCmetrics(\n  spe,\n  metric = \"k80\",\n  outliers = NULL,\n  point_size = 1.1\n) +\n  ggtitle(\"Order 4\")\n\ngridExtra::grid.arrange(p1, p2, p3, p4, ncol = 2)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/hangnail-artifact-validation-1.png){width=672}\n:::\n:::\n\n\nUpon visual inspection, there are no obvious regions with visibly lower variance in mitochondrial proportion. Therefore, we will not filter out hangnail artifacts in the downstream analysis.\n\n\n## Filtering\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# remove the spots considered of low quality based on both global and local metrics\nspe <- spe[, !spe$outliers]\n\n# remove features with all 0 counts\nspe <- spe[rowSums(counts(spe)) > 0, ]\n```\n:::\n\n\n## Save the filtered data\n\n::: {.cell}\n\n```{.r .cell-code}\nsaveHDF5SummarizedExperiment(\n  spe,\n  dir = hdf_data_path,\n  prefix = \"02_qc_\",\n  replace = TRUE,\n  chunkdim = NULL,\n  level = NULL,\n  as.sparse = NA,\n  verbose = NA\n)\n```\n:::\n\n\n:::{.callout-tip collapse=\"true\"}\n## Expand for Session Info\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nR version 4.5.2 (2025-10-31)\nPlatform: x86_64-conda-linux-gnu\nRunning under: Ubuntu 22.04.4 LTS\n\nMatrix products: default\nBLAS/LAPACK: /home/kim/workspace/spatial_transcriptomics/.pixi/envs/default/lib/libopenblasp-r0.3.30.so;  LAPACK version 3.12.0\n\nlocale:\n [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              \n [3] LC_TIME=de_CH.UTF-8        LC_COLLATE=en_US.UTF-8    \n [5] LC_MONETARY=de_CH.UTF-8    LC_MESSAGES=en_US.UTF-8   \n [7] LC_PAPER=de_CH.UTF-8       LC_NAME=C                 \n [9] LC_ADDRESS=C               LC_TELEPHONE=C            \n[11] LC_MEASUREMENT=de_CH.UTF-8 LC_IDENTIFICATION=C       \n\ntime zone: Europe/Zurich\ntzcode source: system (glibc)\n\nattached base packages:\n[1] stats4    stats     graphics  grDevices utils     datasets  methods  \n[8] base     \n\nother attached packages:\n [1] patchwork_1.3.2             ggspavis_1.16.0            \n [3] HDF5Array_1.38.0            h5mread_1.2.0              \n [5] rhdf5_2.54.0                DelayedArray_0.36.0        \n [7] SparseArray_1.10.0          S4Arrays_1.10.0            \n [9] abind_1.4-8                 Matrix_1.7-3               \n[11] escheR_1.10.0               ggside_0.4.0               \n[13] scater_1.38.0               ggplot2_4.0.0              \n[15] scuttle_1.20.0              SpotSweeper_1.6.0          \n[17] SpatialExperiment_1.20.0    SingleCellExperiment_1.32.0\n[19] SummarizedExperiment_1.40.0 Biobase_2.70.0             \n[21] GenomicRanges_1.62.0        Seqinfo_1.0.0              \n[23] IRanges_2.44.0              S4Vectors_0.48.0           \n[25] BiocGenerics_0.56.0         generics_0.1.4             \n[27] MatrixGenerics_1.22.0       matrixStats_1.5.0          \n\nloaded via a namespace (and not attached):\n [1] tidyselect_1.2.1    viridisLite_0.4.2   dplyr_1.1.4        \n [4] vipor_0.4.7         farver_2.1.2        viridis_0.6.5      \n [7] S7_0.2.0            fastmap_1.2.0       digest_0.6.37      \n[10] rsvd_1.0.5          lifecycle_1.0.4     terra_1.8-70       \n[13] dbscan_1.2.3        magrittr_2.0.4      compiler_4.5.2     \n[16] rlang_1.1.6         tools_4.5.2         yaml_2.3.10        \n[19] knitr_1.50          labeling_0.4.3      htmlwidgets_1.6.4  \n[22] RColorBrewer_1.1-3  BiocParallel_1.44.0 withr_3.0.2        \n[25] grid_4.5.2          beachmat_2.26.0     Rhdf5lib_1.32.0    \n[28] scales_1.4.0        MASS_7.3-65         isoband_0.2.7      \n[31] dichromat_2.0-0.1   cli_3.6.5           rmarkdown_2.30     \n[34] rjson_0.2.23        ggbeeswarm_0.7.2    parallel_4.5.2     \n[37] XVector_0.50.0      vctrs_0.6.5         jsonlite_2.0.0     \n[40] BiocSingular_1.26.0 BiocNeighbors_2.4.0 ggrepel_0.9.6      \n[43] irlba_2.3.5.1       beeswarm_0.4.0      magick_2.9.0       \n[46] glue_1.8.0          codetools_0.2-20    gtable_0.3.6       \n[49] ScaledMatrix_1.18.0 tibble_3.3.0        pillar_1.11.1      \n[52] htmltools_0.5.8.1   rhdf5filters_1.22.0 R6_2.6.1           \n[55] evaluate_1.0.5      lattice_0.22-7      Rcpp_1.1.0         \n[58] gridExtra_2.3       xfun_0.53           spatialEco_2.0-3   \n[61] pkgconfig_2.0.3    \n```\n:::\n:::\n\n:::",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}