{
  "hash": "5c33f3b44804a5845f3fffe79d3e1504",
  "result": {
    "markdown": "---\ntitle: \"Spatial Transcriptomics Data Analysis Tutorial 01: Preparation\"\ndescription: \"This tutorial covers the preparation steps for spatial transcriptomics data analysis using Bioconductor.\"\nauthor:\n  - name: Youngjun Kim\n    url: https://yjkim93.github.io\n    orcid: 0000-0003-3346-9457\ndate: 12-21-2025\ncategories: [spatial-transcriptomics, bioconductor, R]\ncitation:\n  url: https://yjkim93.github.io/posts/2025-12-21-spatial-transcriptomics-01-preparation/\ndraft: false\nexecute:\n  warning: false\neditor: source\n---\n\n\n# 1. Preparation\n\n## Load packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(SpatialExperiment)\nlibrary(VisiumIO)\nlibrary(arrow)\nlibrary(qs2)\nlibrary(ggspavis)\nlibrary(patchwork)\nlibrary(dplyr)\nlibrary(arrow)\nlibrary(scuttle)\nlibrary(HDF5Array)\n```\n:::\n\n\n## Load Data\n\nMy data is stored in the following path. Please change the path accordingly.\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_path <- \"/home/kim/workspace/spatial_transcriptomics/data\"\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nvisium_data_path <- file.path(data_path, \"raw_colon_cancer\")\nhdf_data_path <- file.path(data_path, \"hdf5_colon_cancer\")\n```\n:::\n\n\nVisium HD spots are arranged as 2 × 2 µm squares. Space Ranger outputs data at three bin sizes: 2 µm, 8 µm, and 16 µm. Smaller bin sizes provide higher spatial resolution but result in greater data sparsity. In this tutorial, we use a bin size of 16 µm.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspe <- TENxVisiumHD(\n  spacerangerOut = visium_data_path,\n  processing = \"filtered\",\n  format = \"h5\",\n  images = \"lowres\",\n  bin_size = \"016\"\n) |>\n  import()\n```\n:::\n\n\n## Taking a peek at the data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(spe)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]  18085 127809\n```\n:::\n:::\n\n\nThe dataset contains 127,809 spots and 18,085 genes.\n\nBecause *SpatialExperiment* is an extension of *SingleCellExperiment*, it uses a similar data structure: the count matrix is organized with genes as rows and spots as columns. If you are more familiar with Python’s *AnnData* and *scanpy*, note that this orientation is the transpose of what you may expect.\n\n![](https://github.com/drighelli/SpatialExperiment/raw/devel/vignettes/SPE.png)\n\nMetadata for spots and genes can be accessed using `colData(spe)` and `rowData(spe)`, respectively.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spot metadata\nhead(colData(spe))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDataFrame with 6 rows and 6 columns\n                                    barcode in_tissue array_row array_col\n                                <character> <integer> <integer> <integer>\ns_016um_00052_00082-1 s_016um_00052_00082-1         1        52        82\ns_016um_00010_00367-1 s_016um_00010_00367-1         1        10       367\ns_016um_00163_00399-1 s_016um_00163_00399-1         1       163       399\ns_016um_00238_00388-1 s_016um_00238_00388-1         1       238       388\ns_016um_00144_00175-1 s_016um_00144_00175-1         1       144       175\ns_016um_00297_00147-1 s_016um_00297_00147-1         1       297       147\n                         bin_size   sample_id\n                      <character> <character>\ns_016um_00052_00082-1         016    sample01\ns_016um_00010_00367-1         016    sample01\ns_016um_00163_00399-1         016    sample01\ns_016um_00238_00388-1         016    sample01\ns_016um_00144_00175-1         016    sample01\ns_016um_00297_00147-1         016    sample01\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Gene metadata\nhead(rowData(spe))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDataFrame with 6 rows and 3 columns\n                             ID      Symbol            Type\n                    <character> <character>        <factor>\nENSG00000187634 ENSG00000187634      SAMD11 Gene Expression\nENSG00000188976 ENSG00000188976       NOC2L Gene Expression\nENSG00000187961 ENSG00000187961      KLHL17 Gene Expression\nENSG00000187583 ENSG00000187583     PLEKHN1 Gene Expression\nENSG00000187642 ENSG00000187642       PERM1 Gene Expression\nENSG00000188290 ENSG00000188290        HES4 Gene Expression\n```\n:::\n:::\n\n\nSince the current row names are Ensembl ID, we update them to gene symbols for easier downstream analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrownames(spe) <- uniquifyFeatureNames(\n  ID = rowData(spe)$ID,\n  names = rowData(spe)$Symbol\n)\n```\n:::\n\n\nThe count matrix itself can be accessed using `counts(spe)`.\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(counts(spe))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<6 x 127809> sparse DelayedMatrix object of type \"integer\":\n        s_016um_00052_00082-1 ... s_016um_00144_00329-1\nSAMD11                      0   .                     0\nNOC2L                       0   .                     0\nKLHL17                      0   .                     0\nPLEKHN1                     0   .                     0\nPERM1                       0   .                     0\nHES4                        0   .                     0\n```\n:::\n:::\n\n\nOne of the data specific to spatial transcriptomics is the spatial coordinates of each spot, which can be accessed using `spatialCoords(spe)`.\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(spatialCoords(spe))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                      pxl_col_in_fullres pxl_row_in_fullres\ns_016um_00052_00082-1           4592.154           33582.69\ns_016um_00010_00367-1          21222.637           36191.27\ns_016um_00163_00399-1          23176.077           27266.75\ns_016um_00238_00388-1          22574.200           22877.49\ns_016um_00144_00175-1          10076.365           28256.34\ns_016um_00297_00147-1           8523.582           19299.57\n```\n:::\n:::\n\n\nWe can also visualize the spatial distribution of spots on the tissue slide using the `plotVisium()` function from the *ggspavis* package.\n\n::: {.cell}\n\n```{.r .cell-code}\nplotVisium(spe)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/plot-image-1.png){width=672}\n:::\n:::\n\n\nBased on the plot, we can see the tissue section and the spots that map to the tissue. It seems that the data is already filtered to retain only spots that map to the tissue. We can confirm this by checking the `in_tissue` column in the `colData(spe)`.\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(spe$in_tissue)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n     1 \n127809 \n```\n:::\n:::\n\n\nWe can also visualize the expression of a specific gene on the tissue slide. For example, we can visualize the expression of the gene `PIGR`.\n\n::: {.cell}\n\n```{.r .cell-code}\nplotVisium(\n  spe,\n  annotate = \"PIGR\",\n  assay = \"counts\",\n  point_size = 1,\n  point_shape = 22\n)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/plot-gene-expression-1.png){width=672}\n:::\n:::\n\n\n## Subsetting the data\n\nSince the dataset is large, we will subset a smaller region for faster processing. To decide which region to subset, we zoom in on the tissue section where the spots are mapped using `zoom = TRUE` option. Also, we show the axes using `show_axes = TRUE` option to help us decide the bounding box coordinates.\n\n::: {.cell}\n\n```{.r .cell-code}\nplotVisium(spe, spots = FALSE, zoom = TRUE, show_axes = TRUE)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/plot-zoomed-1.png){width=672}\n:::\n:::\n\n\nThe x and y axes values denotes `scalefactor` * `spatialCoords`. From the plot, we will subset the bounding box with the following coordinates:\n\n- xmin: 70\n- ymin: 200\n- xsize: 60\n- ysize: 60\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbb_xmin <- 70\nbb_ymin <- 200\nbb_xsize <- 60\nbb_ysize <- 60\n\ngetSubsetMask <- function(spe, xmin, ymin, xsize, ysize) {\n  mask <-\n    spatialCoords(spe)[, 1] * scaleFactors(spe) > xmin &\n    spatialCoords(spe)[, 1] * scaleFactors(spe) < (xmin + xsize) &\n    spatialCoords(spe)[, 2] * scaleFactors(spe) > ymin &\n    spatialCoords(spe)[, 2] * scaleFactors(spe) < (ymin + ysize)\n  return(mask)\n}\n\nspe <- spe[, getSubsetMask(spe, bb_xmin, bb_ymin, bb_xsize, bb_ysize)]\ndim(spe)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18085 14207\n```\n:::\n:::\n\n\nAfter subsetting, there are 14,207 spots remaining. We can also visualize the subsetted region\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplotVisium(spe, spots = TRUE)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/plot-subsetted-1.png){width=672}\n:::\n:::\n\n\n## Save the subsetted data\n\n::: {.cell}\n\n```{.r .cell-code}\nsaveHDF5SummarizedExperiment(\n  spe,\n  dir = hdf_data_path,\n  prefix = \"01_subsetted_\",\n  replace = TRUE,\n  chunkdim = NULL,\n  level = NULL,\n  as.sparse = NA,\n  verbose = NA\n)\n```\n:::\n\n\n:::{.callout-tip collapse=\"true\"}\n## Expand for Session Info\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nR version 4.5.2 (2025-10-31)\nPlatform: x86_64-conda-linux-gnu\nRunning under: Ubuntu 22.04.4 LTS\n\nMatrix products: default\nBLAS/LAPACK: /home/kim/workspace/spatial_transcriptomics/.pixi/envs/default/lib/libopenblasp-r0.3.30.so;  LAPACK version 3.12.0\n\nlocale:\n [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              \n [3] LC_TIME=de_CH.UTF-8        LC_COLLATE=en_US.UTF-8    \n [5] LC_MONETARY=de_CH.UTF-8    LC_MESSAGES=en_US.UTF-8   \n [7] LC_PAPER=de_CH.UTF-8       LC_NAME=C                 \n [9] LC_ADDRESS=C               LC_TELEPHONE=C            \n[11] LC_MEASUREMENT=de_CH.UTF-8 LC_IDENTIFICATION=C       \n\ntime zone: Europe/Zurich\ntzcode source: system (glibc)\n\nattached base packages:\n[1] stats4    stats     graphics  grDevices utils     datasets  methods  \n[8] base     \n\nother attached packages:\n [1] HDF5Array_1.38.0            h5mread_1.2.0              \n [3] rhdf5_2.54.0                DelayedArray_0.36.0        \n [5] SparseArray_1.10.0          S4Arrays_1.10.0            \n [7] abind_1.4-8                 Matrix_1.7-3               \n [9] scuttle_1.20.0              dplyr_1.1.4                \n[11] patchwork_1.3.2             ggspavis_1.16.0            \n[13] ggplot2_4.0.0               qs2_0.1.5                  \n[15] arrow_22.0.0                VisiumIO_1.6.0             \n[17] TENxIO_1.12.0               SpatialExperiment_1.20.0   \n[19] SingleCellExperiment_1.32.0 SummarizedExperiment_1.40.0\n[21] Biobase_2.70.0              GenomicRanges_1.62.0       \n[23] Seqinfo_1.0.0               IRanges_2.44.0             \n[25] S4Vectors_0.48.0            BiocGenerics_0.56.0        \n[27] generics_0.1.4              MatrixGenerics_1.22.0      \n[29] matrixStats_1.5.0          \n\nloaded via a namespace (and not attached):\n [1] tidyselect_1.2.1      farver_2.1.2          R.utils_2.13.0       \n [4] S7_0.2.0              fastmap_1.2.0         stringfish_0.17.0    \n [7] digest_0.6.37         lifecycle_1.0.4       magrittr_2.0.4       \n[10] compiler_4.5.2        rlang_1.1.6           tools_4.5.2          \n[13] yaml_2.3.10           knitr_1.50            labeling_0.4.3       \n[16] htmlwidgets_1.6.4     bit_4.6.0             RColorBrewer_1.1-3   \n[19] BiocParallel_1.44.0   withr_3.0.2           purrr_1.1.0          \n[22] R.oo_1.27.1           grid_4.5.2            beachmat_2.26.0      \n[25] Rhdf5lib_1.32.0       scales_1.4.0          dichromat_2.0-0.1    \n[28] cli_3.6.5             rmarkdown_2.30        RcppParallel_5.1.11-1\n[31] tzdb_0.5.0            rjson_0.2.23          BiocBaseUtils_1.12.0 \n[34] assertthat_0.2.1      parallel_4.5.2        XVector_0.50.0       \n[37] vctrs_0.6.5           jsonlite_2.0.0        hms_1.1.4            \n[40] bit64_4.6.0-1         ggrepel_0.9.6         magick_2.9.0         \n[43] ggside_0.4.0          glue_1.8.0            codetools_0.2-20     \n[46] gtable_0.3.6          BiocIO_1.20.0         tibble_3.3.0         \n[49] pillar_1.11.1         htmltools_0.5.8.1     rhdf5filters_1.22.0  \n[52] R6_2.6.1              evaluate_1.0.5        lattice_0.22-7       \n[55] readr_2.1.5           R.methodsS3_1.8.2     Rcpp_1.1.0           \n[58] xfun_0.53             pkgconfig_2.0.3      \n```\n:::\n:::\n\n:::",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}